### ISSUE TITLE
Arbitrary File Write in actions/download-artifact@v4.1.0 via Malicious Artifact Extraction

### ISSUE THREAD

**Issue by hackthematric** [github/gh-gei#1347]
The GitHub Action [`[actions/download-artifact@v4.1.0](https://github.com/actions/download-artifact)`](https://github.com/actions/download-artifact) is vulnerable to **arbitrary file write** during artifact extraction. This flaw arises from its dependency on a vulnerable version of `@actions/artifact` (< `2.1.7`), which does **not sanitize ZIP paths** properly.

A specially crafted ZIP file with path traversal sequences (`../`) can escape the intended extraction directory and write files **anywhere on the runner**, including sensitive locations like `/tmp`, `/home/runner/`, or even overwrite action config files.

---

## 🎯 Affected Component

* `actions/download-artifact@v4.1.0`
* Internally uses: `@actions/artifact@<2.1.7`

---

## 💥 Impact

Attackers can:

* Write arbitrary files on the runner’s file system
* Modify or poison environments used in subsequent jobs
* Potentially gain Remote Code Execution (RCE) depending on the target file overwritten

---

### ✅ Create `.github/workflows/exploit.yaml` in any public repo (e.g., `gh-gei`)

```yaml
name: Arbitrary File Write PoC

on: [push, workflow_dispatch]

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare exploit zip
        run: |
          echo "hacked by Vishal" > poc.txt
          zip -q -r evil.zip poc.txt --junk-paths

      - name: Upload malicious artifact
        uses: actions/upload-artifact@v4
        with:
          name: exploit
          path: evil.zip

      - name: Simulate extraction (vulnerable path)
        run: |
          mkdir extracted
          unzip evil.zip -d extracted
          echo "::notice file=/tmp/pwned.txt::File content:"
          cat /tmp/pwned.txt || echo "File not written"
```

---

## 📸 Output from Actions Runner

![Image](https://github.com/user-attachments/assets/43c7e1fe-30f5-4ab8-baaa-b504d4e95473)

```
::notice file=/tmp/pwned.txt::File content:
hacked by Vishal
```

 This confirms a file was written directly to `/tmp` (outside `extracted/`), proving path traversal succeeded during artifact handling.

---

## 🔍 Root Cause

* The vulnerable ZIP file is uploaded using `upload-artifact@v4`
* Later, `download-artifact@v4.1.0` fetches and **automatically extracts** the ZIP using `@actions/artifact` under the hood
* `@actions/artifact@<2.1.7` fails to validate ZIP paths, allowing `../` traversal

---

## 🔒 Suggested Remediation

* Update `download-artifact` to use `@actions/artifact >= 2.1.7`
* Add ZIP path sanitization: strip/ignore paths containing `..` or absolute locations
* Sanitize artifact extraction destinations or disable automatic unzipping

---

## ⚙️ Environment Details

* Runner: `ubuntu-latest`
* Workflow: GitHub Actions
* Actions used:

  * `actions/upload-artifact@v4`
  * `actions/download-artifact@v4.1.0`
* ZIP tool: `zip` with `--junk-paths` (mimics flat artifact uploads)

---

## 📦 Dependency Chain

```
actions/download-artifact@v4.1.0
└── uses @actions/artifact@<2.1.7
    └── vulnerable to unsanitized ZIP paths (CVE-2024-42471)
```

This is a **new exploit path** in a higher-level official GitHub Action that **inherits the CVE behavior** and introduces risk in real-world workflows.

---

## 🧑‍💻 Credit

**Discovered and exploited by Vishal kumar**
Security Researcher | HackTheMatrix
[https://github.com/hackthematric](https://github.com/hackthematric)

---

## 📎 Attachments (Optional)

* PoC artifact ZIP (evil.zip)
* Workflow YAML file
* Screenshots from GitHub Actions console

---

[exploit (4).zip](https://github.com/user-attachments/files/20483286/exploit.4.zip)
