### ISSUE TITLE
`workflow_dispatch` fires on migration but no Runners configured

### ISSUE THREAD

**Issue by toddoconnor** [github/gh-gei#476]
We have a `workflow_dispatch` event in an Action in a repo that was migrated from GHEC to GHEC w/EMU. 

```
on:
  workflow_dispatch:
  schedule:
    - cron: '4,14,24,34,44,54 * * * *'
```

The Action is still active in the new EMU repo but since there are no Runners configured in either the migrated repo or the new Org this Action fails. Maybe it's not a good practice to run Actions via a `cron` none the less I wanted to report this behavior that we have seen in this migration.
